from scipy.stats import chi2
from remodels.qra.tester import QR_TestResults
from pathlib import Path
import numpy as np

# Disclaimer: this code was generated by Claude 4.6
# Prompt: "Please give me helper functions that 1) allow me to calculate QRA error metrics per year and 2) hlep me calculate the Christoffersen test's results per hour"
base = Path(__file__).parents[1]
data_dir = base / "data" / "qra"


def subset_year(results, index, year):
    idx = np.where(index.year == year)[0]
    if len(idx) == 0:
        return None
    s, e = int(idx[0]), int(idx[-1]) + 1
    return QR_TestResults(results.Y_pred[s:e], results.y_test[s:e], results.prediction_window)


def christoffersen_per_hour(results, alpha, significance):
    alpha_p = alpha / 100
    hits = results._hits(alpha)
    pw = results.prediction_window
    threshold = chi2.ppf(1 - significance, df=2)
    not_rejected = np.zeros(pw, dtype=bool)
    for h in range(pw):
        stat = results._christoffersen_test_statistic(hits[h::pw], alpha_p)
        not_rejected[h] = stat < threshold
    return not_rejected
