import numpy as np
from remodels.transformers.StandardizingScaler import StandardizingScaler
from scipy.stats import norm
import pandas as pd

def mad_median(arr):
    """
    Compute the Median Absolute Deviation of an array
    """
    median = np.median(arr)
    dev = np.abs(arr-median)
    return np.median(dev)

class MedianStandardizingScaler(StandardizingScaler):
    """
    Extend the StandardizingSclaer class to overwrite mean-based mad-function with mad_median
    """
    def _compute_center_scale(self, data):
        if self.method == "median":
            center = np.median(data)
            scale = mad_median(data) / norm.ppf(0.75)
        else:
            center = np.mean(data)
            scale = np.std(data)
        # prevent zero divison 
        scale = 1 if scale == 0 else scale
        return center, scale
    
# Code augmented by Claude Sonnet 4.6.
# Prompt: 'Can you help me fix this error: (thesis) benanderer@Mac prob-da-forecast % python data/forecasts/point_pred_transform.py
# /Users/benanderer/Library/Mobile Documents/com~apple~CloudDocs/Repositories/prob-da-forecast/helpers/standardization.py:41: RuntimeWarning: overflow encountered in sinh
#  return np.sinh(y_hat[:, None] + residuals[None, :]).mean(axis=1) * scale + center
def inverse_transform_asinh(y_hat: np.ndarray, residuals: np.ndarray, 
                             center: float, scale: float) -> np.ndarray:
    """
    Bias-corrected inverse asinh transformation (Narajewski & Ziel, 2020).
    
    y_hat     : predicted values in transformed space, shape (n,)
    residuals : in-sample residuals, shape (D,)
    center    : μ from median standardization
    scale     : σ from median standardization
    """
    arg = np.clip(y_hat[:, None] + residuals[None, :], -500, 500) # Clipping required to avoid overflow
    return np.sinh(arg).mean(axis=1) * scale + center


# Code generated by Claude Sonnet 4.6.
# Prompt: 'Please reshape the dataframes. Right now, they have 24x4 columns: 1 column for each hour and calibration window lengh. I need the dataframes to have on row for each hour on a given day and the columns should be for the different calibration windows. '
def reshape_forecast(df):
    """
    Reshape the dfs back to the original date-format where each row is an hour.
    Columns are the point forecasts for 6m, 12m, 18m and 24m calibration windows
    """
    long = df.stack().reset_index()
    long.columns = ['date', 'col', 'value']
    long['hour'] = long['col'].str.extract(r'h(\d+)_').astype(int)
    long['window'] = long['col'].str.extract(r'_(\d+m)')
    long['datetime'] = pd.to_datetime(long['date']) + pd.to_timedelta(long['hour'], unit='h')
    result = long.pivot_table(index='datetime', columns='window', values='value')
    result.columns.name = None
    return result[['6m', '12m', '18m', '24m']]
