"""
Implement feedback from Lion: count how many times overall each feature was selected
"""
# Disclaimer: Code generated by Claude Sonnet 4.6
# Prompt: Please use my helpers from models/lear/model.py to generate print statements
# which detail the parameter selection count per market and calibration window
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parents[1]))
import pandas as pd
from models.lear.model import rolling_lear_coefs


def main():
    base = Path(__file__).parents[1]
    test_days = pd.date_range(start='2020-01-01', end='2025-09-30')

    windows = {         
        '6m' : 182,
        '12m': 364,
        '18m': 546,
        '24m': 728,
    }

    markets = {
        'Germany': base / 'data/processed/ger_merged.csv',
        'Spain'  :   base / 'data/processed/es_merged.csv',
    }

    fractions = {}   # (market, window) 
    raw_counts = {}  # (market, window) 

    for market_name, data_path in markets.items():
        print(f"\n{'='*60}")
        print(f"Market: {market_name}")
        print(f"{'='*60}")

        df = pd.read_csv(data_path, index_col=0, parse_dates=True)
        target_col  = df.columns[0]
        feature_cols = list(df.columns[1:])

        for window_label, cal_days in windows.items():
            print(f"  calibration window: {window_label}  ({cal_days} days) …", flush=True)

            selected, total = rolling_lear_coefs(
                df, feature_cols, target_col, cal_days, test_days
            )

            fractions[(market_name, window_label)] = pd.Series(
                selected / total, index=feature_cols
            )
            raw_counts[(market_name, window_label)] = pd.Series(
                [f"{s} / {total}" for s in selected], index=feature_cols
            )
            print(f"    done — {total} fits ({total // 24} valid days)", flush=True)

    # ── Assemble DataFrames ───────────────────────────────────────────────────

    fraction_df = pd.DataFrame(fractions)
    fraction_df.columns = pd.MultiIndex.from_tuples(
        fraction_df.columns, names=['Market', 'Window']
    )

    count_df = pd.DataFrame(raw_counts)
    count_df.columns = pd.MultiIndex.from_tuples(
        count_df.columns, names=['Market', 'Window']
    )

    # ── Save ─────────────────────────────────────────────────────────────────

    out_dir = Path(__file__).parent
    fraction_df.to_csv(out_dir / 'lear_selection_rates.csv')
    count_df.to_csv(out_dir   / 'lear_selection_counts.csv')

    # ── Print summary ─────────────────────────────────────────────────────────

    print('\n\n' + '='*70)
    print('FEATURE SELECTION RATES  (fraction of fits with non-zero coefficient)')
    print('='*70)
    print(fraction_df.to_string(float_format=lambda x: f'{x:.4f}'))

    print('\n\n' + '='*70)
    print('RAW COUNTS  (selected / total fits)')
    print('='*70)
    print(count_df.to_string())

    print(f"\nSaved:\n  {out_dir / 'lear_selection_rates.csv'}"
          f"\n  {out_dir / 'lear_selection_counts.csv'}")


if __name__ == '__main__':
    main()
