# Disclaimer: Code generated by Claude 4.6
# Prompt: drawing on my code in tests/lear_eval.py, can you help me make a graph like this for the lear_eval? I'd like to have Germany and Spain in the graph and want the graph to display in which hours the models (6m, 12m, 18m, 24m) beat the benchmark. The benchmark counts as beaten if the p-value of the DM test is 0.05 and below
import matplotlib
matplotlib.use('Agg')   # non-interactive backend — no blocking plt.show()
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from pathlib import Path
from epftoolbox.evaluation import DM
from models.naive_benchmark import naive_benchmark

BASE = Path(__file__).parents[1]
MODELS = ['6m', '12m', '18m', '24m']

# ── colour map (mirrors epftoolbox style) ──────────────────────────────────────
red   = np.concatenate([np.linspace(0, 1, 50), np.linspace(1, 0.5, 50)[1:], [0]])
green = np.concatenate([np.linspace(0.5, 1, 50), np.zeros(50)])
blue  = np.zeros(100)
rgb   = np.stack([red, green, blue], axis=1)
CMAP  = mpl.colors.ListedColormap(rgb)


def _align_common_idx(full_idx, bench_idx):
    """Keep only dates where all 24 h are present in both index sets."""
    common = full_idx.intersection(bench_idx)
    dates  = pd.Series(common.date)
    complete = dates[dates.map(dates.value_counts()) == 24].unique()
    return common[pd.Series(common.date).isin(complete).values]


def compute_pvalues(market: str) -> pd.DataFrame:
    """Return DataFrame (models × 24 hours) of DM p-values for *market*."""
    # load forecasts & actuals
    forecasts = pd.read_csv(
        BASE / f'data/forecasts/{market}_point_pred_clean.csv',
        index_col=0, parse_dates=True
    )
    merged = pd.read_csv(
        BASE / f'data/processed/{market}_merged.csv',
        index_col=0, parse_dates=True
    )
    full = forecasts.merge(merged['day_ahead_price_eur_mwh'],
                           how='inner', left_index=True, right_index=True)

    # naive benchmark
    bench = naive_benchmark.seasonal_naive_forecast(df=merged)
    bench = bench.loc[full.index].dropna()

    # align to complete days
    idx = _align_common_idx(full.index, bench.index)

    p_real  = merged.loc[idx, 'day_ahead_price_eur_mwh'].values.reshape(-1, 24)
    p_bench = bench.loc[idx, 'forecast_naive_bench_eur_mwh'].values.reshape(-1, 24)

    rows = {}
    for model in MODELS:
        p_lear = full.loc[idx, model].values.reshape(-1, 24)
        rows[model] = DM(p_real=p_real, p_pred_1=p_bench, p_pred_2=p_lear,
                         norm=1, version='univariate')

    return pd.DataFrame(rows, index=range(24)).T   # shape: (4 models × 24 hours)


# ── compute ────────────────────────────────────────────────────────────────────
print("Computing DM tests for Germany …")
ger_pv = compute_pvalues('ger')
print("Computing DM tests for Spain …")
es_pv  = compute_pvalues('es')

# ── plot ───────────────────────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 4), constrained_layout=True)

VMAX = 0.1   # colour scale saturates at 0.10 (anything above = black)
SIG  = 0.05  # significance threshold

for ax, pv, title in [(axes[0], ger_pv, 'Germany'),
                      (axes[1], es_pv,  'Spain')]:
    im = ax.imshow(pv.values.astype(float), cmap=CMAP, vmin=0, vmax=VMAX,
                   aspect='auto')

    # white × on every cell; filled white square on significant cells (mirrors reference style)
    for r, model in enumerate(MODELS):
        for c in range(24):
            p = pv.loc[model, c]
            if p <= SIG:
                # significant: white × mark (matches the reference figure's diagonal style)
                ax.plot(c, r, 'wx', markersize=7, markeredgewidth=1.5)
            else:
                # not significant: small grey × so non-beating cells are visually distinct
                ax.plot(c, r, color='grey', marker='x', markersize=4,
                        markeredgewidth=0.8, linestyle='none', alpha=0.4)

    ax.set_xticks(range(24))
    ax.set_xticklabels(range(24), fontsize=8)
    ax.set_yticks(range(len(MODELS)))
    ax.set_yticklabels(MODELS, fontsize=10)
    ax.set_xlabel('Hour of day', fontsize=10)
    ax.set_title(title, fontweight='bold', fontsize=12)

    # draw grid lines between cells for clarity
    ax.set_xticks(np.arange(-0.5, 24, 1), minor=True)
    ax.set_yticks(np.arange(-0.5, len(MODELS), 1), minor=True)
    ax.grid(which='minor', color='white', linewidth=0.5)
    ax.tick_params(which='minor', length=0)

# shared colour bar
cbar = fig.colorbar(im, ax=axes, orientation='vertical', fraction=0.025, pad=0.02)
cbar.set_label('DM test p-value', fontsize=10)
# mark significance threshold on the colorbar
cbar.ax.axhline(SIG / VMAX, color='white', linewidth=2, linestyle='--')
cbar.ax.text(1.6, SIG / VMAX, 'p=0.05', va='center', fontsize=8,
             transform=cbar.ax.transAxes, color='white')

fig.suptitle(
    'One-Sided DM Test: LEAR Models vs Naive Benchmark\n'
    r'White X = model significantly better ($p \leq 0.05$); black = not significant',
    fontsize=11
)

out_path = BASE / 'results/figures/lear/dm_heatmap.png'
out_path.parent.mkdir(parents=True, exist_ok=True)
fig.savefig(out_path, dpi=200, bbox_inches='tight')
print(f"Saved → {out_path}")
