from os import path

import matplotlib.pyplot as plt
from pathlib import Path
import pandas as pd

UKRAINE_WAR_DATE = pd.Timestamp('2022-02-24')

# Disclaimer: the following code was generated by Claude 4.6
# Prompt: please create one more figure for Germany and Spain, called {country}_{version}_lear_final_thesis_fig.png. It should show the following: 
#- stack the plots for LEAR benchmark, 6m, and 24m calibration on top of each other (in this order)
#- have a shared x-axis as well as the same y-lims (-250 to 250 for Germany, -150 to 150 for Spain)
#- the smoothign should be 1 day, not 7 days

#Make two versions:
#- one with the scatter
#- one with a 1 std. band around the smoothed line instead of the scatter
# Only one panel legend is needed, and please give each plot a main title: {Country} LEAR residuals, and use subtitles for the subplots --> 
# Benchmark, 6m Calibration Window, 24m Calibration Window. Also, each panel should have a label a), b), c)

# Thesis figures: benchmark / 6m / 24m stacked, shared x-axis, 1-day smoothing
_subplot_letters = ['a)', 'b)', 'c)']
_subplot_titles  = ['Benchmark', '6m Calibration Window', '24m Calibration Window']

def make_thesis_fig(country_label, panels, ylim, version, save_path):
    smooth_win = 24*7  # 7 days
    fig, axes = plt.subplots(len(panels), 1, figsize=(14, 4 * len(panels)), sharex=True)
    fig.suptitle(f'{country_label} LEAR Residuals', fontsize=14, fontweight='bold')
    for i, (ax, (residuals, subtitle)) in enumerate(zip(axes, panels)):
        smoothed = residuals.rolling(window=smooth_win, center=True).mean()
        if version == 'scatter':
            ax.scatter(residuals.index, residuals, s=.5, color='steelblue', alpha=0.4)
            ax.plot(smoothed.index, smoothed, color='red', linewidth=1, label='7-day smoothed avg.')
        else:  # band
            rolling_std = residuals.rolling(window=24, center=True).std()
            ax.fill_between(smoothed.index, smoothed - rolling_std, smoothed + rolling_std,
                            color='steelblue', alpha=0.4, label='±1 std. (daily)')
            ax.plot(smoothed.index, smoothed, color='red', linewidth=1, label='7-day smoothed avg.')
        ax.axhline(0, color='black', linewidth=0.8, linestyle='--')
        ax.axvline(UKRAINE_WAR_DATE, color='black', linestyle='--', linewidth=0.9, alpha=0.8, label='Outbreak Ukraine War')
        ax.set_ylim(ylim)
        ax.set_title(f'{_subplot_letters[i]} {subtitle}', loc='left')
        ax.set_ylabel('Residual (€/MWh)')
        if i == 0:
            ax.legend(loc='upper right')
    axes[-1].set_xlabel('Date')
    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close(fig)

ger_lear_thesis  = pd.read_csv(Path(__file__).parents[1] / 'data/residuals/ger_lear_residuals.csv', index_col=0, parse_dates=True)
es_lear_thesis   = pd.read_csv(Path(__file__).parents[1] / 'data/residuals/es_lear_residuals.csv',  index_col=0, parse_dates=True)
ger_bench_thesis = pd.read_csv(Path(__file__).parents[1] / 'data/forecasts/ger_point_benchmark.csv', index_col=0, parse_dates=True)
es_bench_thesis  = pd.read_csv(Path(__file__).parents[1] / 'data/forecasts/es_point_benchmark.csv',  index_col=0, parse_dates=True)

for country, lear_data, bench_data, ylim in [
    ('ger', ger_lear_thesis, ger_bench_thesis, (-250, 250)),
    ('es',  es_lear_thesis,  es_bench_thesis,  (-150, 150)),
]:
    country_label = 'Germany' if country == 'ger' else 'Spain'
    panels = [
        (bench_data['residuals'], _subplot_titles[0]),
        (lear_data['res_6m'],     _subplot_titles[1]),
        (lear_data['res_24m'],    _subplot_titles[2]),
    ]
    for version in ('scatter', 'band'):
        save_path = Path(__file__).parents[1] / f'results/figures/{country}_{version}_lear_final_thesis_fig.png'
        make_thesis_fig(country_label, panels, ylim, version, save_path)