from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


### Germany ###
qra_path = Path(__file__).parents[1] / 'data/qra/ger_qra_sorted.csv'
qra_data = pd.read_csv(qra_path, index_col=0, parse_dates=True)
actual_path = Path(__file__).parents[1] / 'data/processed/ger_merged.csv'
actual_data = pd.read_csv(actual_path, index_col=0, parse_dates=True)

forecast_start = qra_data.index[0]


fig, ax = plt.subplots(figsize=(14, 5))
ax.plot(actual_data.index,  actual_data['day_ahead_price_eur_mwh'].rolling(window=24*2, center=True, min_periods=1).mean(), color='black', alpha=0.5, linewidth= 0.8, label='Actual (1-day smoothed)')
ax.fill_between(
    qra_data.index,
    qra_data['qra_pred_05'].rolling(window=24*1, center=True, min_periods=1).mean() , # i tried smoothing here, but it totally obscured the message. Best to keep it to a minimum
    qra_data['qra_pred_95'].rolling(window=24*1, center=True, min_periods=1).mean(),
    color='red', alpha=0.8, label='QRA 5%–95% interval (1-day smoothed)'
)
ax.axvline(forecast_start, color='black', linewidth=0.8, linestyle='--', label='Forecast period start')
ax.set_ylim(-50, 650)  # this cuts some outliers out and I will have to mention it in the discussion
ax.set_title('Germany: QRA Forecast vs Actual')
ax.set_ylabel('Price (€/MWh)')
ax.set_xlabel('Date')
ax.legend(loc='upper right')
plt.tight_layout()
plt.savefig('results/figures/qra/ger_qra.png', dpi=150)
plt.close(fig)


###  Interval Width 
interval_width_ger = (qra_data['qra_pred_95'] - qra_data['qra_pred_05']).rolling(window=24*1, center=True, min_periods=1).mean()

fig, ax = plt.subplots(figsize=(14, 5))
ax.plot(qra_data.index, qra_data['qra_pred_05'].rolling(window=24*1, center=True, min_periods=1).mean(), color='red', alpha=0.5, linewidth=0.8, label= 'QRA P5 interval (1-day smoothed)' )
ax.plot(qra_data.index, qra_data['qra_pred_95'].rolling(window=24*1, center=True, min_periods=1).mean(), color='blue', alpha=0.5, linewidth=0.8, label= 'QRA P95 interval (1-day smoothed)' )
ax.plot(interval_width_ger.index, interval_width_ger, color='black', alpha=0.8, linewidth=0.8, label='Q5–Q95 interval width (1-day smoothed)')
ax.set_title('Germany: QRA Q5–Q95 Interval Width')
ax.set_ylabel('Interval Width (€/MWh)')
ax.set_xlabel('Date')
ax.legend(loc='upper right')
plt.tight_layout()
plt.savefig('results/figures/qra/ger_qra_width.png', dpi=150)
plt.close(fig)


### Spain ###
qra_path = Path(__file__).parents[1] / 'data/qra/es_qra_sorted.csv'
qra_data = pd.read_csv(qra_path, index_col=0, parse_dates=True)
actual_path = Path(__file__).parents[1] / 'data/processed/es_merged.csv'
actual_data = pd.read_csv(actual_path, index_col=0, parse_dates=True)

forecast_start = qra_data.index[0]

fig, ax = plt.subplots(figsize=(14, 5))

ax.plot(actual_data.index,  actual_data['day_ahead_price_eur_mwh'].rolling(window=24*2, center=True, min_periods=1).mean(), color='black', alpha=0.5, linewidth= 0.8, label='Actual (1-day smoothed)')
ax.fill_between(
    qra_data.index,
    qra_data['qra_pred_05'].rolling(window=24*2, center=True, min_periods=1).mean() , # i tried smoothing here, but it totally obscured the message. Best to keep it to a minimum
    qra_data['qra_pred_95'].rolling(window=24*2, center=True, min_periods=1).mean(),
    color='red', alpha=0.8, label='QRA Q5–Q95 interval (1-day smoothed)'
)
ax.axvline(forecast_start, color='black', linewidth=0.8, linestyle='--', label='Forecast period start')
ax.set_ylim(-20, 500)  # this cuts some outliers out and I will have to mention it in the discussion
ax.set_title('Spain: QRA Forecast vs Actual')
ax.set_ylabel('Price (€/MWh)')
ax.set_xlabel('Date')
ax.legend(loc='upper right')
plt.tight_layout()
plt.savefig('results/figures/qra/es_qra.png', dpi=150)
plt.close(fig)


###  Interval Width
interval_width_es = (qra_data['qra_pred_95'] - qra_data['qra_pred_05']).rolling(window=24*2, center=True, min_periods=1).mean()

fig, ax = plt.subplots(figsize=(14, 5))
ax.plot(interval_width_es.index, interval_width_es, color='black', alpha=0.8, linewidth=0.8, label='Q5–Q95 interval width (1-day smoothed)')
ax.plot(qra_data.index, qra_data['qra_pred_05'].rolling(window=24*1, center=True, min_periods=1).mean(), color='red', alpha=0.5, linewidth=0.8, label= 'P5 Forecast (1-day smoothed)' )
ax.plot(qra_data.index, qra_data['qra_pred_95'].rolling(window=24*1, center=True, min_periods=1).mean(), color='blue', alpha=0.5, linewidth=0.8, label= 'P95 Forecast (1-day smoothed)' )
ax.set_title('Spain: QRA Q5–Q95 Interval Width')
ax.set_ylabel('Interval Width (€/MWh)')
ax.set_xlabel('Date')
ax.legend(loc='upper right')
plt.tight_layout()
plt.savefig('results/figures/qra/es_qra_width.png', dpi=150)
plt.close(fig)


# Disclaimer: the following code was generated by Claude 4.6
# Prompt: I would like you to add something at the bottom of this script:
# please generate a plot that shows the width of Q5 to Q95 as a band (like in the lear_final_thesis_plot) and plots the price as a red line.
# I want a plot like this for Germany and Spain, same naming convention as with lear_final_thesis_plot and please save it to the figures/qra.
# Both plots' x-axes should only start with the beginning of the QRA-forecast data.
# The y-axis should be -50 to 650 for Germany and -20 to 500 for Spain. Mark the outbreak of the Ukraine war.

UKRAINE_WAR_DATE = pd.Timestamp('2022-02-24')

for country, qra_file, actual_file, smooth_win, price_ylim in [
    ('ger', 'data/qra/ger_qra_sorted.csv', 'data/processed/ger_merged.csv', 24*1, (-50, 650)),
    ('es',  'data/qra/es_qra_sorted.csv',  'data/processed/es_merged.csv',  24*1, (-20, 500)),
]:
    country_label = 'Germany' if country == 'ger' else 'Spain'
    qra    = pd.read_csv(Path(__file__).parents[1] / qra_file,    index_col=0, parse_dates=True)
    actual = pd.read_csv(Path(__file__).parents[1] / actual_file, index_col=0, parse_dates=True)

    q05   = qra['qra_pred_05'].rolling(window=smooth_win, center=True, min_periods=1).mean()
    q95   = qra['qra_pred_95'].rolling(window=smooth_win, center=True, min_periods=1).mean()
    price = actual['day_ahead_price_eur_mwh'].rolling(window=smooth_win, center=True, min_periods=1).mean()

    fig, ax = plt.subplots(figsize=(14, 5))
    ax.fill_between(qra.index, q05, q95, color='steelblue', alpha=0.4, label='Q5–Q95 interval (1-day smoothed)')
    ax.plot(actual.index, price, color='red', linewidth=0.8, alpha=0.7, label='Actual price (1-day smoothed)')
    ax.axvline(UKRAINE_WAR_DATE, color='black', linestyle='--', linewidth=0.9, alpha=0.8, label='Outbreak Ukraine War')
    ax.set_xlim(qra.index[0], qra.index[-1])
    ax.set_ylim(price_ylim)
    ax.set_ylabel('Price (€/MWh)')
    ax.set_xlabel('Date')
    ax.set_title(f'{country_label}: QRA Q5–Q95 Prediction Interval vs. Actual Price')
    ax.legend(loc='upper right')
    plt.tight_layout()
    plt.savefig(Path(__file__).parents[1] / f'results/figures/qra/{country}_qra_thesis_fig.png', dpi=150, bbox_inches='tight')
    plt.close(fig)


# Prompt: And now one last thing: for Spain and Germany I want the same plots, but one starting with the QRA forecast
# data beginning and spanning 1 year, and one starting in September 2021 and going until 31.12.2022.
# They should be saved as separate plots. Everything else should be the same as above.


for country, qra_file, actual_file, smooth_win, price_ylim in [
    ('ger', 'data/qra/ger_qra_sorted.csv', 'data/processed/ger_merged.csv', 24*1, (-50, 650)),
    ('es',  'data/qra/es_qra_sorted.csv',  'data/processed/es_merged.csv',  24*1, (-20, 500)),
]:
    country_label = 'Germany' if country == 'ger' else 'Spain'
    qra    = pd.read_csv(Path(__file__).parents[1] / qra_file,    index_col=0, parse_dates=True)
    actual = pd.read_csv(Path(__file__).parents[1] / actual_file, index_col=0, parse_dates=True)

    q05   = qra['qra_pred_05'].rolling(window=smooth_win, center=True, min_periods=1).mean()
    q95   = qra['qra_pred_95'].rolling(window=smooth_win, center=True, min_periods=1).mean()
    price = actual['day_ahead_price_eur_mwh'].rolling(window=smooth_win, center=True, min_periods=1).mean()

    zoom1_start = qra.index[0]
    zoom1_end   = zoom1_start + pd.DateOffset(years=1)
    zoom2_start = pd.Timestamp('2021-09-01')
    zoom2_end   = pd.Timestamp('2022-12-31')

    for suffix, xlim in [('zoom1', (zoom1_start, zoom1_end)), ('zoom2', (zoom2_start, zoom2_end))]:
        fig, ax = plt.subplots(figsize=(14, 5))
        ax.fill_between(qra.index, q05, q95, color='steelblue', alpha=0.4, label='Q5–Q95 interval (1-day smoothed)')
        ax.plot(actual.index, price, color='red', linewidth=0.8, alpha=0.7, label='Actual price (1-day smoothed)')
        ax.axvline(UKRAINE_WAR_DATE, color='black', linestyle='--', linewidth=0.9, alpha=0.8, label='Outbreak Ukraine War')
        ax.set_xlim(xlim)
        ax.set_ylim(price_ylim)
        ax.set_ylabel('Price (€/MWh)')
        ax.set_xlabel('Date')
        ax.set_title(f'{country_label}: QRA Q5–Q95 Prediction Interval vs. Actual Price')
        ax.legend(loc='upper right')
        plt.tight_layout()
        plt.savefig(Path(__file__).parents[1] / f'results/figures/qra/{country}_qra_{suffix}_thesis_fig.png', dpi=150, bbox_inches='tight')
        plt.close(fig)


# Prompt: Make a figure that stacks the two zoomed views on top of each other in a single plot.

for country, qra_file, actual_file, smooth_win, price_ylim in [
    ('ger', 'data/qra/ger_qra_sorted.csv', 'data/processed/ger_merged.csv', 24*1, (-50, 650)),
    ('es',  'data/qra/es_qra_sorted.csv',  'data/processed/es_merged.csv',  24*1, (-20, 500)),
]:
    country_label = 'Germany' if country == 'ger' else 'Spain'
    qra    = pd.read_csv(Path(__file__).parents[1] / qra_file,    index_col=0, parse_dates=True)
    actual = pd.read_csv(Path(__file__).parents[1] / actual_file, index_col=0, parse_dates=True)

    q05   = qra['qra_pred_05'].rolling(window=smooth_win, center=True, min_periods=1).mean()
    q95   = qra['qra_pred_95'].rolling(window=smooth_win, center=True, min_periods=1).mean()
    price = actual['day_ahead_price_eur_mwh'].rolling(window=smooth_win, center=True, min_periods=1).mean()

    zoom1_start = pd.Timestamp('2021-01-01')
    zoom1_end   = pd.Timestamp('2021-12-31')
    zoom2_start = pd.Timestamp('2022-01-01')
    zoom2_end   = pd.Timestamp('2022-12-31')

    fig, axes = plt.subplots(2, 1, figsize=(14, 8))
    for ax, xlim, label in [
        (axes[0], (zoom1_start, zoom1_end),   'a)'),
        (axes[1], (zoom2_start, zoom2_end),   'b)'),
    ]:
        ax.fill_between(qra.index, q05, q95, color='steelblue', alpha=0.4, label='Q5–Q95 interval (1-day smoothed)')
        ax.plot(actual.index, price, color='red', linewidth=0.8, alpha=0.7, label='Actual price (1-day smoothed)')
        ax.axvline(UKRAINE_WAR_DATE, color='black', linestyle='--', linewidth=0.9, alpha=0.8, label='Outbreak Ukraine War')
        ax.set_xlim(xlim)
        ax.set_ylim(price_ylim)
        ax.set_ylabel('Price (€/MWh)')
        ax.set_title(f'{label} {xlim[0].year}', loc='left')
        ax.legend(loc='upper right', fontsize=8)
    handles, labels = axes[0].get_legend_handles_labels()
    axes[0].legend(
        [h for h, l in zip(handles, labels) if l != 'Outbreak Ukraine War'],
        [l for l in labels if l != 'Outbreak Ukraine War'],
        loc='upper right', fontsize=8,
    )
    axes[1].set_xlabel('Date')
    fig.suptitle(f'{country_label}: QRA Q5–Q95 Prediction Interval vs. Actual Price - Zoomed Views', fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig(Path(__file__).parents[1] / f'results/figures/qra/{country}_qra_zoom_thesis_fig.png', dpi=150, bbox_inches='tight')
    plt.close(fig)
